DROP TABLE IF EXISTS STUDENTE;
DROP TABLE IF EXISTS APPELLO;
DROP TABLE IF EXISTS ESAME;
DROP TABLE IF EXISTS PRENOTAZIONE;

CREATE TABLE STUDENTE
(
    MATRICOLA        INTEGER PRIMARY KEY,
    NOME_STUDENTE    TEXT NOT NULL,
    COGNOME_STUDENTE TEXT NOT NULL,
    PIANO_DI_STUDI   TEXT,
    PASSWORD         TEXT NOT NULL
);

CREATE TABLE ESAME
(
    ID_ESAME       INTEGER PRIMARY KEY,
    NOME_ESAME     TEXT    NOT NULL,
    CFU            INTEGER NOT NULL,
    CORSO_DI_STUDI TEXT    NOT NULL
);

CREATE TABLE APPELLO
(
    ID_APPELLO   INTEGER PRIMARY KEY,
    NOME_APPELLO TEXT NOT NULL,
    DATA_APPELLO DATE NOT NULL,
    ID_ESAME     INTEGER,
    FOREIGN KEY (ID_ESAME) REFERENCES ESAME (ID_ESAME)
);

CREATE TABLE PRENOTAZIONE
(
    ID_PRENOTAZIONE   INTEGER,
    MATRICOLA         INTEGER,
    ID_APPELLO        INTEGER,
    DATA_PRENOTAZIONE DATE,
    PRIMARY KEY (ID_PRENOTAZIONE),
    FOREIGN KEY (MATRICOLA) REFERENCES STUDENTE (MATRICOLA),
    FOREIGN KEY (ID_APPELLO) REFERENCES APPELLO (ID_APPELLO)
);
